name: vedb_analysis
channels:
  - anaconda
  - conda-forge
  - auto 
  - vedb
dependencies:
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - ipython
  - pillow
  - imageio
  - h5py
  - pyyaml
  - seaborn
  - pandas
  - appdirs
  - python-couchdb
  - opencv=4.2.0
  - msgpack-python
  - pip
  - pip:
    - git+https://github.com/piecesofmindlab/file_io@main
    - git+https://github.com/vedb/vedb-gaze@main
    - git+https://github.com/vedb/vedb-store@main
